import Navbar from "@/components/common/Navbar.jsx";
import "./globals.css";
import Footer from "@/components/common/footer.jsx";
import MainLayout from "@/components/layouts/MainLayout.jsx";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from 'react-hot-toast';



export const metadata = {
  title: "Vinrich Resort",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <Navbar />
        <MainLayout> 
          <div className="min-h-screen bg-resort-bg bg-cover bg-center bg-no-repeat">
            <div className="bg-white/30 min-h-screen">
              {children}
              <Toaster position="top-right" />
            </div>
          </div>
          <Footer />
        </MainLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
